### ISSUE TITLE
Compile always fails no matter the platform

### ISSUE THREAD

**Issue by GrelTheL** [nstbayless/gml-beautify#2]
Compiling the program always fails, no matter the operating system, hardware or whatever.

- Expected Behavior: for the program to compile successfully.

- Observed Behavior: The program always errors out in compilation. See error below.
Windows Error: https://img.redshirt.dev/lightcoraloutstandinghatchetfish.png
Linux Error: https://img.redshirt.dev/vapidthriftyarabianoryx.png
More linux errors: https://cdn.discordapp.com/attachments/390226097876500481/662954594069905418/20200104_104442.jpg
The file 'parser.h' does not seem to exist within the repository at all.

**Comment by nstbayless** [comment]
Reverted commit causing this error.
